require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ToDoSaing' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'ToDoSaingTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'ToDoSaing-tvOS' do
  # Pods for ToDoSaing-tvOS

  target 'ToDoSaing-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
